export declare const PRICE_LINE_TEXTURE: unique symbol;
export declare const POOL_ROUND_TEXTURE: unique symbol;
export declare const LOCK_ICON_TEXTURE: unique symbol;
export declare const DOWN_WAGET_TEXTURE: unique symbol;
export declare const UP_WAGET_TEXTURE: unique symbol;
export declare const SILVER_LEVEL_TEXTURE: unique symbol;
export declare const GOLD_LEVEL_TEXTURE: unique symbol;
export declare const ROYAL_LEVEL_TEXTURE: unique symbol;
export declare const LOCK_COUNTDOWN_TEXTURE: unique symbol;
