export const PRICE_LINE_TEXTURE: symbol = Symbol('PRICE_LINE_TEXTURE')
export const POOL_ROUND_TEXTURE: symbol = Symbol('POOL_ROUND_TEXTURE')
export const LOCK_ICON_TEXTURE: symbol = Symbol('LOCK_ICON_TEXTURE')
export const DOWN_WAGET_TEXTURE: symbol = Symbol('DOWN_WAGET_TEXTURE')
export const UP_WAGET_TEXTURE: symbol = Symbol('UP_WAGET_TEXTURE')
