export const PRICE_LINE_TEXTURE = Symbol('PRICE_LINE_TEXTURE')

export const DOWN_WAGET_TEXTURE = Symbol('DOWN_WAGET_TEXTURE')
export const UP_WAGET_TEXTURE = Symbol('UP_WAGET_TEXTURE')

export const SILVER_LEVEL_TEXTURE = Symbol('SILVER_LEVEL_TEXTURE')
export const GOLD_LEVEL_TEXTURE = Symbol('GOLD_LEVEL_TEXTURE')
export const ROYAL_LEVEL_TEXTURE = Symbol('ROYAL_LEVEL_TEXTURE')

export const LOCK_COUNTDOWN_TEXTURE = Symbol('LOCK_COUNTDOWN_TEXTURE')

export const UP_ICON_TEXTURE = Symbol('UP_ICON_TEXTURE')
export const DOWN_ICON_TEXTURE = Symbol('DOWN_ICON_TEXTURE')
export const ZERO_ICON_TEXTURE = Symbol('ZERO_ICON_TEXTURE')
export const UNDEFINED_ICON_TEXTURE = Symbol('UNDEFINED_ICON_TEXTURE')

export const RESOLUTION_COUNTDOWN_TEXTURE = Symbol('RESOLUTION_COUNTDOWN_TEXTURE')
export const POOL_CLAIM_TEXTURE = Symbol('POOL_CLAIM_TEXTURE')
export const GRADIENT_TEXTURE = Symbol('GRADIENT_TEXTURE')

export const UNKNOWN_DARK_TEXTURE = Symbol('UNKNOWN_DARK_TEXTURE')
export const ETH_DARK_TEXTURE = Symbol('ETH_DARK_TEXTURE')
export const USDT_DARK_TEXTURE = Symbol('USDT_DARK_TEXTURE')
export const USDC_DARK_TEXTURE = Symbol('USDC_DARK_TEXTURE')
export const PARI_DARK_TEXTURE = Symbol('PARI_DARK_TEXTURE')

export const CHAINLINK_TEXTURE = Symbol('CHAINLINK_TEXTURE')
