export const PRICE_LINE_TEXTURE = Symbol('PRICE_LINE_TEXTURE')

export const DOWN_WAGET_TEXTURE = Symbol('DOWN_WAGET_TEXTURE')
export const UP_WAGET_TEXTURE = Symbol('UP_WAGET_TEXTURE')

export const SILVER_LEVEL_TEXTURE = Symbol('SILVER_LEVEL_TEXTURE')
export const GOLD_LEVEL_TEXTURE = Symbol('GOLD_LEVEL_TEXTURE')
export const BRONZE_LEVEL_TEXTURE = Symbol('BRONZE_LEVEL_TEXTURE')

export const LOCK_COUNTDOWN_TEXTURE = Symbol('LOCK_COUNTDOWN_TEXTURE')
export const RESOLUTION_COUNTDOWN_TEXTURE = Symbol('RESOLUTION_COUNTDOWN_TEXTURE')
export const WINNING_COUNTDOWN_TEXTURE = Symbol('WINNING_COUNTDOWN_TEXTURE')
export const SHADOW_COUNTDOWN_TEXTURE = Symbol('SHADOW_COUNTDOWN_TEXTURE')

export const UP_ICON_TEXTURE = Symbol('UP_ICON_TEXTURE')
export const DOWN_ICON_TEXTURE = Symbol('DOWN_ICON_TEXTURE')
export const ZERO_ICON_TEXTURE = Symbol('ZERO_ICON_TEXTURE')
export const UNDEFINED_ICON_TEXTURE = Symbol('UNDEFINED_ICON_TEXTURE')

export const GRADIENT_TEXTURE = Symbol('GRADIENT_TEXTURE')

export const UNKNOWN_DARK_TEXTURE = Symbol('UNKNOWN_DARK_TEXTURE')
export const ETH_DARK_TEXTURE = Symbol('ETH_DARK_TEXTURE')
export const USDT_DARK_TEXTURE = Symbol('USDT_DARK_TEXTURE')
export const USDC_TEXTURE = Symbol('USDC_TEXTURE')
export const USDC_LIGHT_TEXTURE = Symbol('USDC_LIGHT_TEXTURE')
export const DEMO_TEXTURE = Symbol('DEMO_TEXTURE')
export const ORCY_TEXTURE = Symbol('ORCY_TEXTURE')
export const PARI_LIGHT_TEXTURE = Symbol('PARI_LIGHT_TEXTURE')

export const CHAINLINK_TEXTURE = Symbol('CHAINLINK_TEXTURE')

export const COIN_SHINE = Symbol('COIN_SHINE')
export const UNKNOWN_CURRENCY_TEXTURE = Symbol('UNKNOWN_CURRENCY_TEXTURE')
export const PARI_GOLD_TEXTURE = Symbol('PARI_GOLD_TEXTURE')
export const PARI_SILVER_TEXTURE = Symbol('PARI_SILVER_TEXTURE')
export const USDC_GOLD_TEXTURE = Symbol('USDC_GOLD_TEXTURE')
export const USDC_SILVER_TEXTURE = Symbol('USDC_SILVER_TEXTURE')
