export declare const MILLISECONDS_IN_DAY: number;
export declare const INVALID_DATE: Date;
export declare const UNIX_MINUTE = 60;
export declare const UNIX_HOUR: number;
export declare const UNIX_DAY: number;
export declare const UNIX_WEEK: number;
export declare const MAX_FRAME_DURATION: number;
export declare const MIN_FRAME_DURATION: number;
export declare const MAX_EXPAND_RATION = 3;
export declare function nowUnixTS(): number;
export declare class Timeframe {
    private readonly eventTarget;
    private readonly onUpdate;
    private _timerfamePreffered;
    private _since;
    private _until;
    private set since(value);
    private set until(value);
    private untilmax;
    private sincemin;
    private get since();
    private get until();
    private readonly zoomevent;
    private readonly pointerdown;
    private readonly pointermove;
    private readonly pointerup;
    private shiftStartingPoint;
    constructor(eventTarget: EventTarget, onUpdate: () => any);
    private shiftstart;
    private shiftprogress;
    private shiftend;
    save(timeframe: any): this;
    get(): {
        since: number;
        until: number;
    };
    destroy(): void;
    actualize(): this;
    private shift;
    private zoom;
}
