import { Duration } from 'moment';
import { EmittedEvent } from '../data/aliases/aliases.emittedEvent';
import { ChartTypes, InputEventTypes } from '../data/enums';
import { IStickChartStyle, IRawPricePoint } from '../data/interfaces';
import { DateRange } from '../utils/utils.range';
export declare class StickChart {
    private width;
    private height;
    private chartType;
    private stickIntervalSize;
    private columnIntervalSize;
    private style;
    private dateRange;
    private data;
    private middlewareRunner;
    private viewport;
    private state;
    private viewConfig;
    private application;
    constructor(width: number, height: number, chartType: ChartTypes, stickIntervalSize: Duration, columnIntervalSize?: Duration, style?: IStickChartStyle, dateRange?: DateRange, data?: IRawPricePoint[]);
    get view(): HTMLCanvasElement;
    private createViewConfig;
    private createDataManager;
    private createState;
    private createViewport;
    create(): void;
    render(): StickChart;
    setChartType(type: ChartTypes): StickChart;
    addData(rawPricePoint: IRawPricePoint): StickChart;
    addInputEventHandler(event: EmittedEvent, type: InputEventTypes): void;
    private throwIfNotCreatedState;
}
