name: Deploy Stickchart to CodeArtifact

on:
  push:
    branches:
      - master
      - staging
    tags:
      - '*'


jobs:
  Deploy:
    name: Deploy Subgraph to non-live cluster
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    # - name: Install npm
    #   run: |
    #     apt update && apt install npm -y
        
    - name: Login to Amazon CodeArtifact
      run: |
        npm run ca:login
        npm init --scope=@oracly -y

    # - name: Test installing pm-stickchart package
    #   run: |
    #     npm install pm-stickchart

    - name: Push package to Amazon CodeArtifact
      run: |
        echo "${{  github.ref_name }}"
        VER=$(cat package.json| jq .'version' | tr -d "\"")
        echo $VER
#        npm publish


        






