import { RenderingContext } from '@rendering';
import { Container } from '../../../lib/pixi';
import { BaseParisRenderer } from './BaseParisRenderer';
export declare class PariTile extends BaseParisRenderer {
    static readonly PARI_TILE_ID: symbol;
    get rendererId(): symbol;
    private nocontestLineStyle;
    private winlineStyle;
    private buttonStyle;
    private groupStyle;
    private stateBackgroundStyle;
    private stateBackgroundAlphaStyle;
    private orphanBackgroundStyle;
    private payoutStyle;
    private profitStyle;
    private iconPositionStyle;
    private levelCurrencyStyle;
    private iconCurrencyStyle;
    private wagerStyle;
    private validPariPositions;
    private configAnimations;
    protected get animations(): any;
    protected updatePari(pool: any, pari: any, context: RenderingContext, container: Container): void;
    private updateLine;
    private updateTile;
    private getPositionIconTextureName;
    private getPariCurrencyIconTextureName;
    private createPositionIcon;
    private createPariCurrencyIcon;
    private createLevelCurrency;
    private createContentContainer;
    private createBackground;
    private createPropagatingBackground;
    private createShadow;
    private getStateBackgroundAlpha;
    private getContentAlpha;
}
